### ISSUE TITLE
not able to log xray in elasticbeanstalk

### ISSUE THREAD

**Issue by Krison13425** [patrickkerrigan/php-xray#19]
`<?php

\Pkerrigan\Xray\Trace::getInstance()
    ->setName('my-app')
    ->setUrl('http:/ss')
    ->setMethod('GET')
    ->begin();

echo ' my function ';

\Pkerrigan\Xray\Trace::getInstance()
    ->end()
    ->setResponseCode(http_response_code())
    ->setError(http_response_code() >= 400 && http_response_code() < 500)
    ->setFault(http_response_code() >= 500)
    ->submit(new \Pkerrigan\Xray\Submission\DaemonSegmentSubmitter());`

above is the code on how i trace my application on elsatco beanstalk 

but i'm not able to get any traces on the xray

**Comment by patrickkerrigan** [comment]
Hi,

That code snippet looks like it should work.

By default this will attempt to submit the trace to an x-ray daemon running on the same machine. Can you confirm whether you've [enabled the x-ray daemon on your Elastic Beanstalk environment](https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-beanstalk.html)?

If that's enabled and running, please can you provide the contents of the x-ray daemon log file?


Thanks

**Comment by Krison13425** [comment]
this is he x-ray log om the elastic beanstalk 

2023/08/03 05:14:21.394919 [INFO] Running command /bin/sh -c systemctl is-active xray.service
2023/08/03 05:14:21.398723 [INFO] Running command /bin/sh -c systemctl start xray.service
2023/08/03 05:14:21.414631 [INFO] Executing instruction: start php-fpm
2023/08/03 05:14:21.415058 [INFO] Running command /bin/sh -c systemctl show -p PartOf php-fpm.service
2023/08/03 05:14:21.426299 [WARN] Warning: process php-fpm is already registered...
Deregistering the process ...
2023/08/03 05:14:21.426320 [INFO] Running command /bin/sh -c systemctl show -p PartOf php-fpm.service
2023/08/03 05:14:21.431988 [INFO] Running command /bin/sh -c systemctl is-active php-fpm.service
2023/08/03 05:14:21.436450 [INFO] Running command /bin/sh -c systemctl disable php-fpm.service
2023/08/03 05:14:21.517327 [INFO] Running command /bin/sh -c systemctl daemon-reload
2023/08/03 05:14:21.616391 [INFO] Running command /bin/sh -c systemctl reset-failed
2023/08/03 05:14:21.621956 [INFO] Running command /bin/sh -c systemctl daemon-reload
2023/08/03 05:14:21.701708 [INFO] Running command /bin/sh -c systemctl reset-failed
2023/08/03 05:14:21.705471 [INFO] Running command /bin/sh -c systemctl show -p PartOf php-fpm.service
2023/08/03 05:14:21.715743 [INFO] Running command /bin/sh -c systemctl is-active php-fpm.service
2023/08/03 05:14:21.719431 [INFO] Running command /bin/sh -c systemctl start php-fpm.service
2023/08/03 05:14:21.822469 [INFO] Executing instruction: start proxy with new configuration
2023/08/03 05:14:21.822509 [INFO] Running command /bin/sh -c /usr/sbin/nginx -t -c /var/proxy/staging/nginx/nginx.conf
2023/08/03 05:14:21.838129 [INFO] nginx: the configuration file /var/proxy/staging/nginx/nginx.conf syntax is ok
nginx: configuration file /var/proxy/staging/nginx/nginx.conf test is successful

2023/08/03 05:14:21.838427 [INFO] Running command /bin/sh -c cp -rp /var/proxy/staging/nginx/* /etc/nginx
2023/08/03 05:14:21.841062 [INFO] Running command /bin/sh -c systemctl show -p PartOf nginx.service
2023/08/03 05:14:21.867537 [INFO] Running command /bin/sh -c systemctl daemon-reload
2023/08/03 05:14:21.961775 [INFO] Running command /bin/sh -c systemctl reset-failed
2023/08/03 05:14:21.966158 [INFO] Running command /bin/sh -c systemctl show -p PartOf nginx.service
2023/08/03 05:14:21.971555 [INFO] Running command /bin/sh -c systemctl is-active nginx.service
2023/08/03 05:14:21.984257 [INFO] Running command /bin/sh -c systemctl start nginx.service
2023/08/03 05:14:22.070369 [INFO] Executing instruction: configureSqsd
2023/08/03 05:14:22.070389 [INFO] This is a web server environment instance, skip configure sqsd daemon ...
2023/08/03 05:14:22.070393 [INFO] Executing instruction: startSqsd
2023/08/03 05:14:22.070396 [INFO] This is a web server environment instance, skip start sqsd daemon ...
2023/08/03 05:14:22.070398 [INFO] Executing instruction: Track pids in healthd
2023/08/03 05:14:22.070401 [INFO] This is an enhanced health env...
2023/08/03 05:14:22.070412 [INFO] Running command /bin/sh -c systemctl show -p ConsistsOf aws-eb.target | cut -d= -f2
2023/08/03 05:14:22.081021 [INFO] amazon-cloudwatch-agent.service cfn-hup.service healthd.service xray.service php-fpm.service nginx.service

2023/08/03 05:14:22.081051 [INFO] Running command /bin/sh -c systemctl show -p ConsistsOf eb-app.target | cut -d= -f2
2023/08/03 05:14:22.086518 [INFO] 

2023/08/03 05:14:22.087114 [INFO] Executing instruction: RunAppDeployPostDeployHooks
2023/08/03 05:14:22.087125 [INFO] Executing platform hooks in .platform/hooks/postdeploy/
2023/08/03 05:14:22.087151 [INFO] The dir .platform/hooks/postdeploy/ does not exist
2023/08/03 05:14:22.087154 [INFO] Finished running scripts in /var/app/current/.platform/hooks/postdeploy
2023/08/03 05:14:22.087160 [INFO] Executing cleanup logic
2023/08/03 05:14:22.087236 [INFO] CommandService Response: {"status":"SUCCESS","api_version":"1.0","results":[{"status":"SUCCESS","msg":"Engine execution has succeeded.","returncode":0,"events":[{"msg":"Instance deployment completed successfully.","timestamp":1691039662087,"severity":"INFO"}]}]}

2023/08/03 05:14:22.087387 [INFO] Platform Engine finished execution on command: app-deploy

2023/08/03 05:15:55.997562 [INFO] Starting...
2023/08/03 05:15:55.997605 [INFO] Starting EBPlatform-PlatformEngine
2023/08/03 05:15:55.997626 [INFO] reading event message file
2023/08/03 05:15:55.997756 [INFO] Engine received EB command cfn-hup-exec

2023/08/03 05:15:56.097047 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-get-metadata -s arn:aws:cloudformation:us-east-1:982002044658:stack/awseb-e-iaeftrrfvr-stack/546f1d30-2f3e-11ee-a121-0a748a371cc5 -r AWSEBAutoScalingGroup --region us-east-1
2023/08/03 05:15:56.497737 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-get-metadata -s arn:aws:cloudformation:us-east-1:982002044658:stack/awseb-e-iaeftrrfvr-stack/546f1d30-2f3e-11ee-a121-0a748a371cc5 -r AWSEBBeanstalkMetadata --region us-east-1
2023/08/03 05:15:56.778492 [INFO] checking whether command bundle-log is applicable to this instance...
2023/08/03 05:15:56.778504 [INFO] this command is applicable to the instance, thus instance should execute command
2023/08/03 05:15:56.778507 [INFO] Engine command: (bundle-log)

2023/08/03 05:15:56.778565 [INFO] Executing instruction: GetBundleLogs
2023/08/03 05:15:56.778569 [INFO] Bundle Logs...

**Comment by patrickkerrigan** [comment]
Thanks for that.

It looks like the x-ray daemon is definitely being started, however, I can't see any output from `xray.log` there.

It looks like you might need to enable collection of that log file by including some configuration as shown at https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-beanstalk.html#xray-daemon-beanstalk-option

Once I can see the output of `xray.log` I should be able to get an idea of where the traces are going missing.

One other thing worth mentioning is that the default behaviour is to trace a 10% sample of requests and ignore the rest. While debugging it might make things easier if you change this so that 100% of requests get traced, which you can do by passing `100` to `begin` when starting the trace, e.g `->begin(100)`

**Comment by Krison13425** [comment]
ok thank you appreciate that

**Comment by Krison13425** [comment]
i have succesfully get the trace on the xray, thank you apprciate that
