### ISSUE TITLE
Add segment with start and end time

### ISSUE THREAD

**Issue by soukicz** [patrickkerrigan/php-xray#4]
Thank you for this great library! We are currently trying to implement it to our project and I wanted to contribute by implementing Doctrine and Symfony.

Best way to implement Doctrine is to use its logger where I can get query details like sanitized query and duration. Problem is that I can't use current segment methods to record query because I can't use begin/end before and after query. I have only end time and duration.
What would be the best solution?
1) add optional arguments with _time_ to _begin_+_end_ methods
2) add new method _setTime($begin, $end)_
3) create new segment class with this implemented and keep it in the new DoctrineXRay package

I will create necessary PR but I just wanted to consult this tiny change first.

**Comment by soukicz** [comment]
Nevermind. Extending of existing SqlSegment is so easy that there is no point in adding extra methods.
I thought it will be lot more complicated to override default behaviour :)

**Comment by patrickkerrigan** [comment]
No worries, glad to hear it was easy to extend!

Let me know if you end up publishing your package on Composer, and I'll add a link to it here if you like
